class InferenceError(Exception): ...


class ModelUnavailableError(Exception): ...


class SellerNotFoundError(Exception): ...

class ItemNotFoundError(Exception): ...

class ModerationResultNotFoundError(Exception): ...

class AccountNotFoundError(Exception): ...

class InvalidCredentialsError(Exception): ...

class AccountBlockedError(Exception): ...

class InvalidTokenError(Exception): ...